compilers_list = {
    "antlr3":	"language tool for constructing recognizers, compilers etc",
    "asn1c":	"ASN.1 compiler for C",
    "bcc":	"16-bit x86 C compiler",
    "bifcl":	"Bro Built-In-Function Compiler",
    "blueprint-compiler":	"Markup language for GTK user interface files",
    "bnfc":	"Compiler front-end generator based on Labelled BNF",
    "boogie":	"verifiable programming language (compiler)",
    "bpfcc-tools":	"tools for BPF Compiler Collection (BCC)",
    "checkpolicy":	"SELinux policy compiler",
    "chezscheme":	"Reliable, high performance Scheme compiler",
    "chicken-bin":	"Practical and portable Scheme systemcompiler",
    "chronicle":	"HTML & RSS blog compiler",
    "cl-regex":	"Common Lisp regular expression compiler/matcher",
    "clang":	"C, C++ and Objective-C compiler (LLVM based), clang binary",
    "clang-15":	"C, C++ and Objective-C compiler",
    "clc-intercal":	"Compiler for the INTERCAL language",
    "clisp":	"GNU CLISP, a Common Lisp implementation",
    "closure-compiler":	"JavaScript optimizing compiler",
    "coco-cpp":	"Coco/R Compiler Generator (C++ Version)",
    "coco-cs":	"Coco/R Compiler Generator (C-Sharp Version)",
    "coco-java":	"Coco/R Compiler Generator (Java Version)",
    "coffeescript":	"interpreter and compiler for the CoffeeScript language",
    "coq":	"proof assistant for higher-order logic (toplevel and compiler)",
    "creduce":	"Test-Case Reduction for C Compiler Bugs",
    "cross-gcc-dev":	"Tools for building cross-compilers and cross-compiler packages",
    "default-d-compiler":	"Default D compiler (metapackage)",
    "device-tree-compiler":	"Device Tree Compiler for Flat Device Trees",
    "distcc":	"simple distributed compiler client and server",
    "distcc-pump":	"pump mode for distcc a distributed compiler client and server",
    "ecj":	"standalone version of the Eclipse Java compiler ",
    "ecl":	"Embeddable Common-Lisp",
    "emscripten":	"LLVM-to-JavaScript Compiler",
    "emscripten-doc":	"LLVM-to-JavaScript Compiler",
    "esnacc":	"ASN.1 to C or C++ or IDL compiler",
    "esnacc-doc":	"ASN.1 to C or C++ or IDL compiler, documentation",
    "f2j":	"Fortran to Java compiler",
    "faucc":	"C compiler generating Intel code for 16bit/32bit CPUs",
    "fauhdlc":	"experimental VHDL compiler and interpreter",
    "flatbuffers-compiler":	"efficient cross platform serialization librarycompiler",
    "flatbuffers-compiler-dev":	"efficient cross platform serialization librarycmake files",
    "fort77":	"Invoke f2c like a real compiler",
    "fp-compiler":	"Free Pascalcompiler dependency package", 
    "fp-compiler-3.2.2":	"Free Pascalcompiler",
    "fsharp":	"functional-first programming languagecompiler for the CLI",
    "fteqcc":	"FTE QuakeC compiler",
    "g++":	"GNU C++ compiler",
    # "g++-9*":	"GNU C++ compiler",
    # "g++-10*":	"GNU C++ compiler",
    # "g++-11":	"GNU C++ compiler",
    # "g++-11*":	"GNU C++ compiler",
    # "g++-12*":	"GNU C++ compiler",
    # "g++-*":	"GNU C++ compiler",
    "g++-9":	"GNU C++ compiler",
    "g++-10":	"GNU C++ compiler",
    "g++-11":	"GNU C++ compiler",
    "g++-11":	"GNU C++ compiler",
    "g++-12":	"GNU C++ compiler",
    "g++-":	"GNU C++ compiler",    
    "gambas3-gb-jit":	"Gambas Just-In-Time compiler component",
    "gambc":	"Gambit Scheme interpreter and compiler",
    "gambc-doc":	"documentation for the Gambit interpreter and compiler",
    "gap-dev":	"GAP computer algebra system, compiler and development files",
    "gcc":	"GNU C compiler",
    # "gcc*":	"GNU C++ compiler",
    # "gcc-*":	"GNU C compiler",
    # "gcc-9*":	"GNU C compiler",
    # "gcc-10*":	"GNU C compiler",
    "gcc-9":	"GNU C compiler",
    "gcc-10":	"GNU C compiler",    
    "gcc-11":	"GNU C compiler",
    # "gcc-11*":	"GNU C compiler",
    "gcc-12-base":	"GCC, the GNU Compiler Collection (base package)",
    "gcc-12":	"GCC, the GNU Compiler Collection (base package)",
    # "gcc-12*":	"GNU C compiler",
    "gccbrig-9":	"GNU BRIG (HSA IL) frontend",
    "gccbrig-9-i686-linux-gnu":	"GNU BRIG (HSA IL) frontend",
    "gccbrig-9-x86-64-linux-gnux32":	"GNU BRIG (HSA IL) frontend",
    "gccbrig-10":	"GNU BRIG (HSA IL) frontend",
    "gccbrig-10-i686-linux-gnu":	"GNU BRIG (HSA IL) frontend",
    "gccbrig-10-x86-64-linux-gnux32":	"GNU BRIG (HSA IL) frontend",
    "gccbrig-11":	"GNU BRIG (HSA IL) frontend",
    "gccbrig-11-i686-linux-gnu":	"GNU BRIG (HSA IL) frontend",
    "gccbrig-11-x86-64-linux-gnux32":	"GNU BRIG (HSA IL) frontend",
    "gccgo":	"Go compiler, based on the GCC backend",
    "gccgo-9":	"GNU Go compiler",
    "gccgo-10":	"GNU Go compiler",
    "gccgo-11":	"GNU Go compiler",
    "gccgo-12":	"GNU Go compiler",
    "gcl":	"GNU Common Lisp compiler",
    "gdc":	"D compiler (language version 2), based on the GCC backend",
    "gdc-9":	"GNU D compiler (version 2)",
    "gdc-10":	"GNU D compiler (version 2)",
    "gdc-11":	"GNU D compiler (version 2)",
    "gdc-12":	"GNU D compiler (version 2)",
    "gfortran":	"GNU Fortran 95 compiler",
    # "gfortran*":	"GNU Fortran compiler",
    "gfortran-9":	"GNU Fortran compiler",
    "gfortran-10":	"GNU Fortran compiler",
    "gfortran-11":	"GNU Fortran compiler",
    # "gfortran-11*":	"GNU Fortran compiler",
    "gfortran-12":	"GNU Fortran compiler",
    "ghc":	"The Glasgow Haskell Compilation system",
    "ghdl":	"VHDL compiler/simulator",
    "gm2":	"GNU Modula-2 compiler, based on the GCC backend",
    # "gm2*":	"GNU Modula-2 compiler, based on the GCC backend",
    "gm2-9":	"GNU Modula-2 compiler",
    "gm2-10":	"GNU Modula-2 compiler",
    "gm2-11":	"GNU Modula-2 compiler",
    "gm2-12":	"GNU Modula-2 compiler",
    "gmcs":	"C# compiler",
    "gnat":	"GNU Ada compiler",
    "gnat-10":	"GNU Ada compiler",
    "gnat-11":	"GNU Ada compiler",
    "gnat-11-alpha-linux-gnu":	"GNU Ada compiler",
    "gnat-12":	"GNU Ada compiler",
    "gnat-9":	"GNU Ada compiler",
    "gnucobol":	"compiler package for default GnuCOBOL",
    "gnucobol3":	"COBOL compiler",
    "gnucobol4":	"COBOL compiler",
    "gnudatalanguage":	"Free IDL compatible incremental compiler",
    "go":	"Go programming language compilermetapackage",
    "gobjc":	"GNU Objective-C compiler",
    "gobjc++":	"GNU Objective-C++ compiler",
    "gobjc++-9":	"GNU Objective-C++ compiler",
    "gobjc++-10":	"GNU Objective-C++ compiler",
    "gobjc++-11":	"GNU Objective-C++ compiler",
    "gobjc++-12":	"GNU Objective-C++ compiler",
    "gobjc-9":	"GNU Objective-C compiler",
    "gobjc-10":	"GNU Objective-C compiler",
    "gobjc-11":	"GNU Objective-C compiler",
    "gobjc-12":	"GNU Objective-C compiler",
    "golang":	"Go programming language compilermetapackage",
    # "golang-*":	"Go programming language compilermetapackage",
    "golang-1.13":	"Go programming language compilermetapackage",
    "golang-1.13-go":	"Go programming language compiler, linker, compiled stdlib",
    "golang-1.17":	"Go programming language compilermetapackage",
    "golang-1.17-go":	"Go programming language compiler, linker, compiled stdlib",
    "golang-github-googleapis-gnostic-dev":	"compiler for OpenAPI specificationlibrary",
    "golang-github-gopherjs-gopherjs-dev":	"Go to Javascript compiler",
    "golang-github-wellington-go-libsass-dev":	"Go wrapper for libsass, the only Sass 3.5 compiler for Go",
    "golang-github-yuin-gopher-lua-dev":	"virtual machine and compiler for Lua in Go",
    "gprconfig-kb":	"compiler list for the gprbuild build tool",
    "gprolog":	"GNU Prolog compiler",
    "gprolog-doc":	"documentation for the GNU Prolog compiler",
    "grcompiler":	"Compiler of smart (graphite) fonts",
    "hidl-gen":	"Compiler for the HIDL",
    "hp48cc":	"C-like compiler which produces HP48 RPN",
    "i8c":	"infinity note compiler",
    "icecc":	"distributed compiler (client and server)",
    "ikarus":	"Scheme compiler and interpreter",
    "ikiwiki":	"wiki compiler",
    "inform":	"story file compiler for the Inform interactive fiction language (v6)",
    "inform6-compiler":	"Inform 6 interactive fiction language aa bb compiler",
    "iverilog":	"Icarus verilog compiler",
    "janino":	"runtime compiler for Java expressionsbinary",
    "js-of-ocaml":	"OCaml bytecode to JavaScript compiler (compiler)",
    "kmflcomp":	"KMFL (Keyboard Mapping for Linux) Compiler",
    "ldc":	"LLVM D Compiler",
    # "llvm*":	"Modular compiler and toolchain technologies",
    "llvm":	"Modular compiler and toolchain technologies",
    "llvm-11":	"Modular compiler and toolchain technologies",
    "llvm-12":	"Modular compiler and toolchain technologies",
    "llvm-13":	"Modular compiler and toolchain technologies",
    "llvm-14":	"Modular compiler and toolchain technologies",
    "luajit":	"Just in time compiler for Lua programming language version 5.1",
    "makedic":	"dictionary compiler for KDrill",
    "mandoc":	"BSD manpage compiler toolset",
    "mono-devel":	"Mono development tools",
    "mono-mcs":	"Mono C# 2.0 / 3.0 / 4.0 / 5.0 compiler for CLI 2.0 / 4.0 / 4.5",
    "mono-vbnc":	"Mono Visual Basic Compiler (VB.NET)",
    "mrc":	"resource compiler to store data in ELF object files",
    "nbc":	"C compiler for LEGO Mindstorms NXT bricks",
    "neko":	"Lightweight virtual machinecompiler and tools",
    "nml":	"newgrf meta language compiler",
    "node":	"JavaScript",
    "node-browserify":	"Node.js compiler for use in the browser",
    "node-buble":	"Fast ES2015 compiler for Node.js",
    "node-css-select":	"CSS selector compiler/engine",
    "node-less":	"LESS CSS meta-languagecompiler and Node module",
    "node-marked":	"Full-featured markdown parser and compiler for NodeJS",
    "node-nth-check":	"performant nth-check parser & compiler",
    "node-snapdragon-util":	"Utilities for the snapdragon parser/compiler",
    "node-transformers":	"String and data transformations using templates and compilers",
    "node-vue":	"Core library of the Vue JavaScript framework",
    "node-webassemblyjs":	"Toolchain for WebAssembly",
    "nqc":	"Not Quite C compiler for LEGO Mindstorms RCX",
    "nqp":	"Not Quite Perl compiler",
    "nqp-data":	"Data files for NQP compiler",
    "nuitka":	"Python compiler with full language support and CPython compatibility",
    "numba-doc":	"native machine code compiler for Python (docs)",
    "nyacc":	"Not Yet Another Compiler Compiler",
    "ocaml":	"ML language implementation with a class-based object system",
    "ocaml-compiler-libs":	"OCaml interpreter and standard libraries",
    "omniidl":	"omniORB IDL to C++ and Python3 compiler",
    # "openjdk-*":	"OpenJDK Development Kit",
    "openjdk-11-jdk":	"OpenJDK Development Kit (JDK)",
    "openjdk-11-jdk-headless":	"OpenJDK Development Kit (JDK) (headless)",
    "openjdk-17-jdk":	"OpenJDK Development Kit (JDK)",
    "openjdk-17-jdk-headless":	"OpenJDK Development Kit (JDK) (headless)",
    "openjdk-18-jdk":	"OpenJDK Development Kit (JDK)",
    "openjdk-18-jdk-headless":	"OpenJDK Development Kit (JDK) (headless)",
    "openjdk-19-jdk":	"OpenJDK Development Kit (JDK)",
    "openjdk-19-jdk-headless":	"OpenJDK Development Kit (JDK) (headless)",
    "openjdk-21-jdk":	"OpenJDK Development Kit (JDK)",
    "openjdk-21-jdk-headless":	"OpenJDK Development Kit (JDK) (headless)",
    "openjdk-8-jdk":	"OpenJDK Development Kit (JDK)",
    "orcc":	"Open RVC-CAL Compiler",
    "pakcs":	"Portland Aachen Kiel Curry Compiler",
    "pari-gp2c":	"PARI/GP GP to C compiler",
    "pcc":	"Portable C Compiler",
    "pccts":	"The Purdue Compiler Construction Tool Set (PCCTS).",
    "polyml":	"interpreter and interactive compiler for Standard ML",
    "polyml-modules":	"modules for Poly/ML, a compiler for Standard ML",
    "procyon-decompiler":	"Procyon Java Decompiler",
    "protobuf-c-compiler":	"Protocol Buffers C compiler (protobuf-c)",
    "protobuf-compiler":	"compiler for protocol buffer definition files",
    "protobuf-compiler-grpc":	"high performance general RPC frameworkprotobuf plugin",
    "protobuf-compiler-grpc-java-plugin":	"high performance general RPC frameworkprotobuf Java plugin",
    "protoc-gen-go":	"Go support for Protocol Buffers (protoc compiler plugin)",
    "python-ffcx-doc":	"next-gen compiler for finite element variational forms (docs)",
    "python-pythran-doc":	"ahead of time compiler for Python (Documentation)",
    "python2":	"compilerPython 2.x",
    "python3":	"compilerPython 3.x",
    "python3-antlr":	"language tool for constructing recognizers, compilers etcPython 3.x",
    "python3-bpfcc":	"Python 3 wrappers for BPF Compiler Collection (BCC)",
    "python3-chameleon":	"XML-based template compiler",
    "python3-ffc":	"compiler for finite element variational forms (Python 3)",
    "python3-ffcx":	"next-gen compiler for finite element variational forms (Python 3)",
    "python3-lesscpy":	"LessCss Compiler for Python 3.x",
    "python3-llvmlite":	"LLVM Python 3 binding for writing JIT compilers",
    "python3-numba":	"native machine code compiler for Python 3",
    "python3-pyscss":	"SCSS compilerPython 3.x",
    "python3-pythran":	"ahead of time compiler for Python",
    "python3-smclib":	"Robot OS 'bond' State Machine Compiler Python 3 package",
    "python3-theano":	"CPU/GPU math expression compiler for Python 3",
    "python3-ufl":	"unified language for form-compilers (Python 3)",
    "rake-compiler":	"Rake-based Ruby Extension (C, Java) task generator",
    "ruby-coffee-script":	"Ruby CoffeeScript Compiler",
    "ruby-ejs":	"EJS (Embedded JavaScript) template compiler",
    "ruby-sass":	"deprecated CSS compileruse sassc or ruby-sassc instead",
    "rust":	"Rust compiler",
    # "rust*":	"Rust compiler",
    "sassc":	"C/C++ port of the Sass CSS precompilercommand-line tool",
    "sbcl":	"Common Lisp compiler and development system",
    "scala-asm":	"Fork of ASM for the Scala Compiler",
    "sdcc":	"Small Device C Compiler",
    "secilc":	"SELinux CIL compiler",
    "shc":	"Shell script compiler",
    "simutrans-makeobj":	"data file compiler for Simutrans",
    "sludge-compiler":	"Compiler for SLUDGE adventure games",
    "smlnj":	"Standard ML of New Jersey interactive compiler",
    "smlsharp":	"Standard ML compiler with practical extensions",
    "snacc":	"ASN.1 to C or C++ or IDL compiler",
    "snacc-doc":	"ASN.1 to C or C++ or IDL compiler, documentation",
    "stalin":	"An extremely aggressive Scheme compiler",
    "tcc":	"small ANSI C compiler",
    "theano-doc":	"CPU/GPU math expression compiler for Python (docs)",
    "thrift-compiler":	"code generator/compiler for Thrift definitions",
    "towncrier":	"compiler for project news file",
    "uil":	"Motif UIL (User Interface Language) compiler",
    "uuagc":	"compiler for the Utrecht University Attribute Grammar system",
    "zeroc-ice-compilers":	"Slice compilers for developing Ice applications"
}